# Generated by Django 5.2.1 on 2025-06-10 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_instrutor_codigo_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 10, 0, 21, 57, 709175, tzinfo=datetime.timezone.utc), help_text='Informe a data de nascimento do Instrutor', null=True),
        ),
    ]
