# Generated by Django 5.2.1 on 2025-06-10 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0003_alter_instrutor_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 10, 0, 36, 54, 688284, tzinfo=datetime.timezone.utc), help_text='Informe a data de nascimento do Instrutor', null=True),
        ),
    ]
