# Generated by Django 5.2.1 on 2025-06-16 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0004_alter_instrutor_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now, help_text='Informe a descrição do Instrutor', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='data_nascimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Informe a data de nascimento do Instrutor', null=True),
        ),
    ]
