# Generated by Django 5.2.1 on 2025-06-10 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_data_final_alter_aluno_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_final',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 10, 0, 21, 57, 709175, tzinfo=datetime.timezone.utc), help_text='Informe a data final de matrícula do Aluno', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 0, 21, 57, 709175, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial de matrícula do Aluno'),
        ),
    ]
