# Generated by Django 5.2.1 on 2025-06-10 00:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_data_final_alter_aluno_data_inicial'),
        ('instrutor', '0003_alter_instrutor_data_nascimento'),
        ('tiposdeatividade', '0003_rename_tipodeatividade_tiposdeatividade'),
        ('turma', '0002_alter_turma_data_final_alter_turma_data_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiposdeatividade.tiposdeatividade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 10, 0, 21, 57, 709175, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 0, 21, 57, 709175, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
