# Generated by Django 5.2.1 on 2025-06-10 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_turma_codigo_atividade_turma_id_instrutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 10, 0, 36, 54, 688284, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 10, 0, 36, 54, 688284, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
